###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: junesc-postgres
      working_dir: /application
      volumes:
        - junesc-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}

    webserver:
      image: nginx:alpine
      container_name: junesc-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: junesc-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./.env:/application/.env

volumes:
  junesc-data: